apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: da-acme-http-prod-cert
spec:
  dnsNames:
  - blog2.gurlal.com #hostname
  secretName: da-acme-http-prod-sec
  issuerRef:
    name: da-acme-http-prod
    kind: ClusterIssuer